---
minimum_pre_commit_version: "2.17"
default_stages: [pre-commit]
default_language_version:
  python: python3.12

ci:
  skip: [mypy, pylint]

repos:
  # ----------------------------------------------
  # Meta hooks
  # ----------------------------------------------

  - repo: meta
    hooks:
      - id: identity
        stages: [pre-commit, manual]
      - id: check-hooks-apply
        stages: [manual]
      - id: check-useless-excludes
        stages: [manual]

  # ----------------------------------------------
  # File hooks
  # ----------------------------------------------

  # file checking out-of-the-box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
        exclude: '^.*\.rs$'
        stages: [pre-commit]
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: forbid-new-submodules

  # ####################################################################################
  #
  #       FORMATTING
  #
  # ####################################################################################

  # ----------------------------------------------
  # Python
  # ----------------------------------------------

  # ruff - python linter with fixing ability
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 2700fd5671c633760d912769c041bfcde2b9a01b # frozen: v0.15.22
    hooks:
      - id: ruff
        name: ruff (fix)
        args: ["--fix-only", "--exit-non-zero-on-fix", "--config=pyproject.toml"]
        exclude: \.pdbrc
      - id: ruff-format
        name: ruff (format)
        exclude: \.pdbrc

  # ----------------------------------------------
  # Markdown
  # ----------------------------------------------

  # markdownlint - md file checker
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: 06f92c99e930c11230426b5edd775021d25e08a8 # frozen: v0.23.1
    # Config file: .markdownlint-cli2.jsonc
    # Inline config:
    # Disable all rules: <!-- markdownlint-disable -->
    # Enable all rules: <!-- markdownlint-enable -->
    # Disable all rules for the next line only: <!-- markdownlint-disable-next-line -->
    # Disable rules by name: <!-- markdownlint-disable MD001 MD005 -->
    # Enable rules by name: <!-- markdownlint-enable MD001 MD005 -->
    # Disable rules by name for next line only: <!-- markdownlint-disable-next-line MD001 MD005 -->
    # Capture the current rule configuration: <!-- markdownlint-capture -->
    # Restore the captured rule configuration: <!-- markdownlint-restore -->
    hooks:
      - id: markdownlint-cli2
        # TODO:#i# lock node version because of bug in node v23 - wait for release
        # https://github.com/nodejs/node/pull/55414
        language_version: 22.18.0
        args: ["--fix"]

  # ----------------------------------------------
  # JS / TS / HTML / CSS / JSON / YAML / MD
  # ----------------------------------------------

  # prettier - multi formatter
  - repo: https://github.com/pre-commit/mirrors-prettier
    # https://github.com/prettier/prettier
    # Config file: "prettier" key package.json | .prettierrc | .prettierrc.json |
    #     https://prettier.io/docs/en/configuration.html
    # Ignore file: .prettierignore [file ignore pattern]
    rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea  # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@^3.3.2 # NOTE: version overwrites rev version - keep in sync
        args: ["--ignore-path", ".gitignore"]
        files: \.(html|css|json,yaml,md)$

  # ----------------------------------------------
  # Spelling dict
  # ----------------------------------------------

  # Custom hook as python command
  - repo: local
    hooks:
      - id: sort-spelling-dicts
        name: Sort spelling_dict.txt files
        description: Sort spelling_dict.txt files
        language: python
        entry: python
        args:
          - "-c"
          - |
            import pathlib;
            import sys;
            p = pathlib.Path(sys.argv[1]);
            p.write_text("\n".join(sorted(set(p.read_text("utf-8").splitlines()))) + "\n", "utf-8")
        files: "spelling_dict.txt"

  # ----------------------------------------------
  # General (code unspecific)
  # ----------------------------------------------

  # code unspecific out-of-the-box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
        exclude: '\.tsx\.snap$'

  # ####################################################################################
  #
  #       LINTING
  #
  # ####################################################################################

  # ----------------------------------------------
  # General (code unspecific)
  # ----------------------------------------------

  # code unspecific out-of-the-box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key

  # ----------------------------------------------
  # Python
  # ----------------------------------------------

  # ruff - python linter with fixing ability
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 2700fd5671c633760d912769c041bfcde2b9a01b # frozen: v0.15.22
    hooks:
      - id: ruff
        name: ruff (lint)
        args: ["--config=pyproject.toml"]
        exclude: \.pdbrc
      - id: ruff-format
        name: ruff (format-check)
        args: ["--diff"]
        exclude: \.pdbrc

  # python specific out-of-the-box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: debug-statements
        exclude: \.pdbrc
      - id: name-tests-test

  # several python code regex hooks
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: 3a6eb0fadf60b3cccfd80bad9dbb6fae7e47b316  # frozen: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn

  # pylint - python linter
  - repo: https://github.com/PyCQA/pylint/
    rev: 8a396357098337ba8be714fffdf2d00947a9778c # frozen: v4.0.6
    hooks:
      # Inline skip file: `# pylint: skip-file`
      # Inline change: `# pylint: disable|enable=CODE|NAME`
      - id: pylint
        name: spell-check (pylint+pyenchant)
        description: >
          spell-check in docstrings/comments in py-source via pyenchant and pylint
        additional_dependencies: [pyenchant]
        args: ["--disable=all", "--enable=spelling", "--rcfile=.pylintrc.spelling.toml"]
        exclude: \.pdbrc

  # ----------------------------------------------
  # Shell script
  # ----------------------------------------------

  # shellscript (via PyPI package)
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 745eface02aef23e168a8afb6b5737818efbea95 # frozen: v0.11.0.1
    hooks:
      - id: shellcheck

  # ----------------------------------------------
  # JSON / TOML / YAML
  # ----------------------------------------------

  # JSON specific out-of-the-box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-json
        exclude: tsconfig\.json|dotfiles/vscodium/\.config/VSCodium/User/keybindings\.json|dotfiles/vscodium/\.config/VSCodium/User/settings\.json
      - id: check-toml
      - id: check-yaml

  # yamllint - yaml linter
  - repo: https://github.com/adrienverge/yamllint
    rev: 79a6b2b1392eaf49cdd32ac4f14be1a809bbd8f7  # frozen: v1.37.1
    hooks:
      # Config file: .yamllint.yaml [--config-file]
      # Inline skip: `# yamllint disable-line[ rule:<RULE>]`
      # Block skip: `# yamllint disable[ rule:<RULE>]`
      # Block skip end: `# yamllint enable`
      - id: yamllint
        exclude: 'pnpm-lock.yaml'
