[tox]
package = <PLACEHOLDER>

minversion = 4
skip_missing_interpreters = true
#: Application -> true; Library -> false
no_package = false

envlist =
    py{312}
    coverage-all


labels =
    test = py312,coverage-all
    3.12 = py312,coverage-all


[global]
coverage_cache = {toxinidir}/.coverage_cache


[testenv]
description = basic config env
deps = pipenv
base_python = python3.12
pass_env =
    HOME
    CI
    PIPENV_CACHE_DIR
set_env =
    PIP_DISABLE_VERSION_CHECK = 1
    PIPENV_VERBOSITY = -1
download = true
commands =
    exit "Please specify existing env"


[testenv:package]
description = check sdist and wheel
skip_install = true
deps =
    poetry >= 1.1.13
    twine >= 3.3
commands =
    poetry build {tty:--ansi:} --no-interaction -vvv
    twine check --strict dist/*


[testenv:mypy]
description = type check python source
set_env =
    PIPENV_VERBOSITY = -1
commands_pre =
    pipenv sync --categories packages,mypy,testing
commands =
    mypy --version

    # TODO:#i# remove feature flag when feature is completly integrated

    mypy \
        --config-file {toxinidir}/pyproject.toml \
        mypy_stubs/asyncmy-stubs/asyncmy-stubs/

    mypy \
        --config-file {toxinidir}/pyproject.toml \
        mypy_stubs/python3-saml-stubs/onelogin-stubs/

    mypy \
        --config-file {toxinidir}/pyproject.toml \
        mypy_stubs/XlsxWriter-stubs/xlsxwriter-stubs/

    mypy \
        --config-file {toxinidir}/pyproject.toml \
        gunicorn.prod.conf.py \
        config.py \
        db_connection.py \
        api \
        api_tests \
        celery_background_tasks


[testenv:py{py3,312,311,310,39}]
description = run tests with {base_python}
pass_env =
    {[testenv]pass_env}
    PYTEST_*
set_env =
    {[testenv]set_env}
    COVERAGE_FILE={[global]coverage_cache}/.coverage.{envname}
    SWLP_QUERY_CACHE_ENABLED_ON_STARTUP=0
commands_pre =
    pipenv sync --categories packages,testing,coverage
commands =
    pytest \
        {tty:--color yes:} \
        --basetemp {envtmpdir} \
        --cov \
        --cov-config {toxinidir}/pyproject.toml \
        --cov-fail-under 0 \
        --junitxml {toxinidir}/.junit_cache/junit.{envname}.xml \
        --numprocesses {env:PYTEST_XDIST_N:auto} \
        {posargs:api_tests}


[testenv:coverage-{all,merge,report}]
description =
    all,merge: combine coverage data and create xml/html reports;
    all,report: report total and diff coverage against origin/master (or DIFF_AGAINST)
envdir = {toxworkdir}/coverage
depends = py{py3,312,311,310,39}
pass_env =
    {[testenv]pass_env}
    all,report: MIN_COVERAGE
    all,report: MIN_DIFF_COVERAGE
    all,report: DIFF_AGAINST
    all,report: DIFF_RANGE_NOTATION
set_env =
    {[testenv]set_env}
    COVERAGE_FILE={[global]coverage_cache}/.coverage
parallel_show_output = true
ignore_errors = true
commands_pre =
    pipenv sync --categories coverage
commands =
    all,merge:  coverage combine \
    all,merge:      --rcfile={toxinidir}/pyproject.toml
    all,merge:  coverage xml -o {[global]coverage_cache}/coverage.xml \
    all,merge:      --rcfile={toxinidir}/pyproject.toml
    all,merge:  coverage html -d {[global]coverage_cache}/htmlcov \
    all,merge:      --rcfile={toxinidir}/pyproject.toml
    all,report: coverage report -m --fail-under {env:MIN_COVERAGE:0} \
    all,report:     --rcfile={toxinidir}/pyproject.toml
    all,report: diff-cover --compare-branch {env:DIFF_AGAINST:origin/main} \
    all,report:     --ignore-staged --ignore-unstaged \
    all,report:     --fail-under {env:MIN_DIFF_COVERAGE:0} \
    all,report:     --diff-range-notation {env:DIFF_RANGE_NOTATION:..} \
    all,report:     {[global]coverage_cache}/coverage.xml


[testenv:docs{,-auto}]
description = build docs with sphinx
envdir = {toxworkdir}/docs
setenv =
    {[testenv]setenv}
    TOXENV_BUILDCMD = sphinx-build {tty:--color:}
    auto: TOXENV_BUILDCMD = sphinx-autobuild
extras = docs
commands =
    # Build fresh docs
    {env:TOXENV_BUILDCMD} -b html -aE docs/source docs/build/html
    # Output link to index.html
    python -c \
       'from pathlib import Path; \
        index_file = Path(r"{toxinidir}")/"docs/build/html/index.html"; \
        print(f"DOCUMENTATION AVAILABLE UNDER: \{index_file.as_uri()\}")'


[testenv:docs-test-{html,linkcheck,coverage,doctest,spelling,confluence}]
description = Build and check docs with (see env name) sphinx builder
envdir = {[testenv:docs]envdir}
setenv =
    {[testenv]setenv}
    html:       TOXENV_BUILDER = html
    linkcheck:  TOXENV_BUILDER = linkcheck
    coverage:   TOXENV_BUILDER = coverage
    doctest:    TOXENV_BUILDER = doctest
    spelling:   TOXENV_BUILDER = spelling
    confluence: TOXENV_BUILDER = confluence
    confluence: TOXENV_ADD_ARGS = -t builder_confluence
extras = {[testenv:docs]extras}
commands =
    sphinx-build {tty:--color:} -b {env:TOXENV_BUILDER} \
        -aE -v -nW --keep-going {env:TOXENV_ADD_ARGS:} \
        docs/source docs/build/test/{env:TOXENV_BUILDER}


[testenv:pre-commit]
description = call any pre-commit command e.g.: `tox -e pre-commit -- autoupdate --freeze`
env_dir = {toxworkdir}/pre-commit
pass_env =
    {[testenv]pass_env}
    SSH_AUTH_SOCK
    SKIP
    PRE_COMMIT_HOME
set_env =
    PIP_DISABLE_VERSION_CHECK = 1
    SKIP = {tty:identity:},{env:SKIP:}
download = true
skip_install = true
deps = pre-commit >= 2.17
commands = pre-commit {posargs}


[testenv:pre-commit-install]
description = install pre-commit as git hook from the tox env
env_dir = {[testenv:pre-commit]env_dir}
pass_env = {[testenv:pre-commit]pass_env}
set_env = {[testenv:pre-commit]set_env}
skip_install = {[testenv:pre-commit]skip_install}
deps = {[testenv:pre-commit]deps}
allowlist_externals = sed
commands =
    pre-commit install -t prepare-commit-msg
    pre-commit install -t commit-msg
    sed -i '5 a export PRE_COMMIT_COLOR=always' {toxinidir}/.git/hooks/prepare-commit-msg
    sed -i '5 a export PRE_COMMIT_COLOR=always' {toxinidir}/.git/hooks/commit-msg


[testenv:pre-commit-uninstall]
description = install pre-commit as git hook from the tox env
env_dir = {[testenv:pre-commit]env_dir}
pass_env = {[testenv:pre-commit]pass_env}
set_env = {[testenv:pre-commit]set_env}
skip_install = {[testenv:pre-commit]skip_install}
deps = {[testenv:pre-commit]deps}
commands =
    pre-commit uninstall -t prepare-commit-msg
    pre-commit uninstall -t commit-msg
